# Repository Configuration
# This file contains recommended settings and metadata for the repository

repository:
  # Recommended repository name
  name: "Veridian"
  
  # Repository description
  description: "Veridian - Modern application platform with advanced features and capabilities"
  
  # Repository visibility
  visibility: "public"
  
  # Repository topics/tags
  topics:
    - "veridian"
    - "platform"
    - "application"
    - "modern"
    - "software"
  
  # Default branch
  default_branch: "main"
  
  # Repository settings
  settings:
    # Enable issues
    has_issues: true
    
    # Enable projects
    has_projects: true
    
    # Enable wiki
    has_wiki: false
    
    # Enable downloads
    has_downloads: true
    
    # Enable auto-merge
    allow_auto_merge: true
    
    # Enable delete branch on merge
    delete_branch_on_merge: true

# Recommended file structure
recommended_structure:
  - "src/"
  - "docs/"
  - "tests/"
  - ".github/"
  - "README.md"
  - "LICENSE"
  - ".gitignore"

# Development guidelines
development:
  language: "JavaScript/TypeScript"
  framework: "Node.js"
  package_manager: "npm"
  
# Contributing guidelines
contributing:
  - "Fork the repository"
  - "Create a feature branch"
  - "Make your changes"
  - "Add tests if applicable"
  - "Submit a pull request"
  - "Ensure CI/CD passes"
